import { StyleSheet } from 'react-native';
import theme, { COMMON, HELPERS, COLORS, FONTS, SIZES } from './theme';

const { wp, hp, moderateScale, verticalScale } = HELPERS;

export const GLOBAL_STYLES = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    alignItems: 'center',
    paddingTop: hp('4%'),
    paddingHorizontal: SIZES.paddingHorizontal,
    borderRadius: moderateScale(25),
  },
  title: {
    fontSize: SIZES.title,
    color: COLORS.primary,
    fontFamily: FONTS.title,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: SIZES.subtitle,
    color: COLORS.secondary,
    marginVertical: hp('1%'),
    fontFamily: FONTS.regular,
    textAlign: 'center',
  },
  inputGroup: {
    width: wp('80%'),
    marginTop: hp('2%'),
  },
  label: {
    fontSize: SIZES.label,
    color: COLORS.secondary,
    fontFamily: FONTS.regular,
    marginBottom: hp('0.5%'),
    marginLeft: wp('1%'),
  },
  input: {
    ...(COMMON.INPUT_BASE as any),
    paddingHorizontal: wp('4%'),
  },
  errorText: {
    color: COLORS.error,
    fontSize: SIZES.smallText,
    marginTop: hp('0.5%'),
  },
  inputPasswordContainer: {
    ...(COMMON.INPUT_CONTAINER as any),
    paddingHorizontal: wp('4%'),
    height: verticalScale(40),
  },
  inputPassword: {
    flex: 1,
    fontSize: SIZES.passwordInput,
    fontFamily: FONTS.regular,
    paddingBottom: 0,
  },
  eyeIconButton: {
    padding: wp('0.1%'),
  },
  recuperarContainer: {
    alignItems: 'flex-end',
    marginTop: hp('0.5%'),
  },
  recuperarPassword: {
    fontSize: SIZES.passwordInput,
    fontFamily: FONTS.regular,
    color: COLORS.accent,
    textDecorationLine: 'underline',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: wp('80%'),
    marginTop: hp('2%'),
  },
  checkbox: {
    width: wp('5%'),
    height: wp('5%'),
    borderWidth: 1,
    borderRadius: 5,
    borderColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp('2%'),
  },
  labelRecordarme: {
    fontSize: SIZES.input,
    color: COLORS.primary,
    fontFamily: FONTS.regular,
  },
  botonLogearse: {
    ...(COMMON.BUTTON_BASE as any),
    ...(COMMON.SHADOW as any),
  },
  textoBotonLogearse: {
    color: COLORS.secondary,
    fontSize: SIZES.buttonText,
    textAlign: 'center',
    fontFamily: FONTS.regular,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  scrollContainer: {
    flexGrow: 1,
    backgroundColor: COLORS.background,
    alignItems: 'center',
    paddingTop: hp('8%'),
    paddingHorizontal: wp('5%'),
  },
  titulo: {
    fontSize: moderateScale(48),
    color: COLORS.primary,
    fontFamily: FONTS.title,
  },
  subtitulo: {
    fontSize: moderateScale(14),
    color: COLORS.accent,
    fontFamily: FONTS.bold,
    marginTop: hp('1%'),
  },
  bloqueTexto: {
    marginTop: hp('1%'),
    alignItems: 'center',
  },
  parrafo: {
    fontSize: moderateScale(13),
    color: '#333',
    textAlign: 'center',
    fontFamily: FONTS.regular,
    width: wp('80%'),
  },
  logo: {
    width: wp('60%'),
    height: wp('60%'),
    marginTop: hp('4%'),
  },
  logoContainer: {
    width: wp('80%'),
    alignItems: 'center',
    marginTop: hp('2%'),
  },
  tituloLogo: {
    fontSize: moderateScale(40),
    color: COLORS.accent,
    fontFamily: FONTS.title,
    textAlign: 'center',
    letterSpacing: 3,
    width: '100%',
  },
  esloganLogo: {
    fontSize: moderateScale(15),
    fontFamily: FONTS.regular,
    textAlign: 'center',
    width: '100%',
    marginTop: -hp('1%'),
    letterSpacing: 1,
  },
  botonCrearCuenta: {
    backgroundColor: COLORS.inputBackground,
    ...(COMMON.BUTTON_BASE as any),
    marginTop: hp('4%'),
    ...(COMMON.SHADOW as any),
  },
  botonIniciarSesion: {
    backgroundColor: COLORS.success,
    ...(COMMON.BUTTON_BASE as any),
    marginBottom: hp('5%'),
    ...(COMMON.SHADOW as any),
  },
  textoBoton: {
    color: COLORS.secondary,
    fontSize: moderateScale(14),
    textAlign: 'center',
    fontFamily: FONTS.regular,
  },
  inputEmailCrearCuenta: {
    ...(COMMON.INPUT_BASE as any),
    marginBottom: verticalScale(5),
    width: wp('80%'),
  },
  botonIngresarMail: {
    paddingVertical: verticalScale(5),
    borderRadius: 15,
    width: wp('80%'),
    alignSelf: 'center',
    marginTop: hp('2%'),
    ...(COMMON.SHADOW as any),
  },
  textoBotonIngresarMail: {
    color: COLORS.secondary,
    fontSize: SIZES.buttonText,
    textAlign: 'center',
    fontFamily: FONTS.regular,
    padding: verticalScale(3),
  },
  recuperarContainerPrincipal: {
    flex: 1,
    backgroundColor: COLORS.background,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: hp('5%'),
    paddingHorizontal: wp('5%'),
    borderRadius: moderateScale(25),
  },
  recuperarBloque: {
    width: wp('80%'),
    alignItems: 'center',
    marginTop: hp('5%'),
  },
  recuperarTitulo: {
    fontSize: wp('10%'),
    color: COLORS.primary,
    fontFamily: FONTS.title,
    textAlign: 'center',
    lineHeight: wp('12%'),
  },
  recuperarSubtitulo: {
    fontSize: wp('3%'),
    color: COLORS.secondary,
    marginVertical: hp('1%'),
    fontFamily: FONTS.regular,
  },
  recuperarLabelCorreo: {
    fontSize: wp('3.5%'),
    alignSelf: 'flex-start',
    marginBottom: hp('0.1%'),
    color: COLORS.secondary,
    fontFamily: FONTS.regular,
  },
  recuperarInput: {
    width: '100%',
    ...(COMMON.INPUT_BASE as any),
    marginBottom: hp('1%'),
  },
  recuperarSubTextEmail: {
    fontFamily: FONTS.regular,
    color: COLORS.secondary,
    fontSize: wp('3%'),
    textAlign: 'justify',
    width: wp('80%'),
    marginTop: hp('1%'),
  },
  botonRecuperarPassword: {
    paddingVertical: hp('1.5%'),
    borderRadius: 15,
    width: wp('80%'),
    alignSelf: 'center',
    marginTop: hp('3%'),
    ...(COMMON.SHADOW as any),
  },
  textoRecuperarPassword: {
    color: COLORS.secondary,
    fontSize: wp('4%'),
    textAlign: 'center',
    fontFamily: FONTS.regular,
  },
  recuperarErrorText: {
    color: COLORS.error,
    fontSize: wp('3.5%'),
    marginTop: hp('0.5%'),
    fontFamily: FONTS.regular,
  },
  botonTemp: {
    paddingVertical: hp('1.5%'),
    borderRadius: 25,
    width: wp('80%'),
    alignSelf: 'center',
    marginTop: hp('20%'),
    ...(COMMON.SHADOW as any),
    backgroundColor: 'red',
  },
  botonTempText: {
    color: '#fff',
    fontSize: moderateScale(14),
    textAlign: 'center',
    fontFamily: FONTS.regular,
  },
  restablecerContainer: {
    ...(COMMON.PAGE_CARD as any),
    borderRadius: moderateScale(15),
  },
  restablecerTitulo: {
    fontSize: moderateScale(45),
    color: COLORS.primary,
    fontFamily: FONTS.title,
    textAlign: 'center',
    lineHeight: moderateScale(55),
  },
  restablecerSubtitulo: {
    fontSize: moderateScale(12),
    color: COLORS.secondary,
    marginVertical: hp('1%'),
    fontFamily: FONTS.regular,
    width: wp('50%'),
    textAlign: 'center',
    marginBottom: hp('1%'),
  },
  restablecerInputGroup: {
    width: wp('80%'),
    marginTop: hp('1%'),
  },
  restablecerLabel: {
    fontSize: SIZES.label,
    color: COLORS.secondary,
    fontFamily: FONTS.regular,
    marginBottom: hp('0.5%'),
  },
  restablecerInputPasswordContainer: {
    ...(COMMON.INPUT_CONTAINER as any),
    borderRadius: moderateScale(15),
    paddingHorizontal: wp('4%'),
    height: verticalScale(40),
  },
  restablecerInputPassword: {
    flex: 1,
    fontSize: SIZES.passwordInput,
    fontFamily: FONTS.regular,
    paddingBottom: 0,
  },
  restablecerEyeIconButton: {
    padding: wp('0.1%'),
  },
  restablecerErrorText: {
    color: COLORS.error,
    fontSize: SIZES.smallText,
    marginTop: hp('0.5%'),
  },
  restablecerBoton: {
    paddingVertical: verticalScale(11),
    borderRadius: 15,
    width: wp('80%'),
    alignSelf: 'center',
    marginTop: hp('4%'),
    ...(COMMON.SHADOW as any),
  },
  restablecerTextoBoton: {
    color: COLORS.secondary,
    fontSize: moderateScale(16),
    textAlign: 'center',
    fontFamily: FONTS.regular,
    padding: verticalScale(3),
  },
  splashContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.background,
  },
  splashLogo: {
    width: 200,
    height: 200,
  },
  splashText: {
    marginTop: 20,
    fontSize: moderateScale(16),
    color: COLORS.secondary,
    fontFamily: FONTS.regular,
  },
  verificacionContainer: {
    ...(COMMON.PAGE_CARD as any),
    borderRadius: moderateScale(25),
  },
  verificacionTitulo: {
    fontSize: moderateScale(45),
    color: COLORS.primary,
    fontFamily: FONTS.title,
    textAlign: 'center',
    lineHeight: moderateScale(55),
  },
  verificacionSubtitulo: {
    fontSize: moderateScale(12),
    color: COLORS.secondary,
    marginVertical: hp('1%'),
    fontFamily: FONTS.regular,
    width: wp('75%'),
    textAlign: 'center',
    marginBottom: hp('1%'),
  },
  verificacionLabelCodigo: {
    marginTop: hp('2%'),
    fontSize: moderateScale(15),
    marginBottom: -2,
    marginLeft: -wp('35%'),
    color: COLORS.secondary,
    fontFamily: FONTS.regular,
  },
  verificacionInputCodigo: {
    ...(COMMON.INPUT_BASE as any),
    fontSize: moderateScale(15),
    marginBottom: verticalScale(5),
    width: wp('80%'),
  },
  verificacionEnviarCodigoNuevo: {
    fontSize: moderateScale(14),
    marginTop: verticalScale(8),
    marginLeft: -wp('45%'),
    fontFamily: FONTS.regular,
    color: COLORS.accent,
  },
  verificacionContador: {
    fontSize: moderateScale(14),
    marginTop: -verticalScale(20),
    marginLeft: wp('75%'),
    fontFamily: FONTS.regular,
    color: COLORS.secondary,
  },
  verificacionContainerPassword: {
    backgroundColor: COLORS.background,
    paddingTop: hp('7%'),
    paddingHorizontal: wp('5%'),
    borderRadius: moderateScale(25),
  },
  verificacionLabelPassword: {
    marginTop: -hp('6%'),
    fontSize: moderateScale(15),
    marginBottom: -2,
    marginLeft: wp('2%'),
    color: COLORS.secondary,
    fontFamily: FONTS.regular,
  },
  verificacionLabelPasswordReq: {
    fontFamily: FONTS.regular,
    color: COLORS.secondary,
    fontSize: moderateScale(11),
    width: wp('80%'),
  },
  verificacionInputPassword: {
    paddingHorizontal: wp('3%'),
    paddingVertical: verticalScale(8),
    fontSize: moderateScale(16),
    width: wp('70%'),
    backgroundColor: COLORS.inputBackground,
    fontFamily: FONTS.regular,
    paddingBottom: 0,
  },
  verificacionInputPasswordContainer: {
    ...(COMMON.INPUT_CONTAINER as any),
    borderRadius: moderateScale(10),
    width: wp('80%'),
    height: verticalScale(38),
    marginBottom: verticalScale(5),
  },
  verificacionEyeIconButton: {
    padding: 0,
    marginLeft: -2,
  },
  verificacionBotonFinalizar: {
    backgroundColor: COLORS.success,
    ...(COMMON.BUTTON_BASE as any),
    marginTop: hp('5%'),
    height: verticalScale(45),
    ...(COMMON.SHADOW as any),
  },
  verificacionTextoBotonFinalizar: {
    color: COLORS.secondary,
    fontSize: moderateScale(16),
    textAlign: 'center',
    fontFamily: FONTS.regular,
    padding: verticalScale(3),
  },
  verificacionOverlay: {
    ...(COMMON.OVERLAY as any),
  },
  verificacionPopup: {
    ...(COMMON.POPUP as any),
  },
  verificacionPopupTextTitle: {
    fontSize: moderateScale(25),
    marginBottom: verticalScale(5),
    textAlign: 'center',
    fontFamily: FONTS.title,
    color: COLORS.primary,
  },
  verificacionPopupTextSubTitle: {
    fontSize: moderateScale(12),
    marginBottom: verticalScale(12),
    textAlign: 'center',
    fontFamily: FONTS.regular,
    color: COLORS.secondary,
  },
  verificacionLogo: {
    width: wp('60%'),
    height: wp('60%'),
    marginTop: -verticalScale(1),
    borderRadius: moderateScale(25),
  },
  verificacionCloseButton: {
    backgroundColor: COLORS.accent,
    paddingVertical: verticalScale(8),
    paddingHorizontal: wp('5%'),
    borderRadius: moderateScale(8),
  },
  verificacionScrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  helperText: {
    fontFamily: FONTS.regular,
    color: COLORS.secondary,
    fontSize: moderateScale(11),
    width: wp('80%'),
  },
  textoBienvenida: {
    fontSize: moderateScale(29),
    color: COLORS.primary,
    fontFamily: FONTS.title,
    textAlign: 'center',
    paddingHorizontal: 19,
  },
  verificacionBotonesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  verificacionCloseButtonText: {
    fontSize: 16,
    color: '#333',
    textAlign: 'center',
  },
  /* Backwards-compatible aliases used by some screens */
  overlay: {
    ...(COMMON.OVERLAY as any),
  },
  popup: {
    ...(COMMON.POPUP as any),
  },
  popupTextTitle: {
    fontSize: moderateScale(25),
    marginBottom: verticalScale(5),
    textAlign: 'center',
    fontFamily: FONTS.title,
    color: COLORS.primary,
  },
  popupTextSubTitle: {
    fontSize: moderateScale(12),
    marginBottom: verticalScale(12),
    textAlign: 'center',
    fontFamily: FONTS.regular,
    color: COLORS.secondary,
  },
  closeButton: {
    backgroundColor: COLORS.accent,
    paddingVertical: verticalScale(8),
    paddingHorizontal: wp('5%'),
    borderRadius: moderateScale(8),
  },
  closeButtonText: {
    fontSize: 16,
    color: '#fff',
    textAlign: 'center',
  },
  checkboxText: {
    fontSize: SIZES.input,
    color: COLORS.primary,
    fontFamily: FONTS.regular,
  },
  buttonLogout: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 15,
    backgroundColor: COLORS.inputBackground,
    marginHorizontal: 15,
    ...(COMMON.SHADOW as any),
  },
  primaryButton: {
    ...(COMMON.BUTTON_BASE as any),
    ...(COMMON.SHADOW as any),
  },
  primaryButtonText: {
    color: COLORS.secondary,
    fontSize: SIZES.buttonText,
    textAlign: 'center',
    fontFamily: FONTS.regular,
  },
  disabledButton: {
    opacity: 0.8,
  },
});

// Backwards-compatible named exports for existing imports
export { COLORS, FONTS, SIZES };

export default GLOBAL_STYLES;
